### PR TITLE
AI Branch

### PR DESCRIPTION
**Pull request by jsnorek**
Added OpenAI endpoint for text summarization as well as individual component testing

### CODE REVIEW

**Comment by jsnorek** [comment]
Can you please review? @marjanasarker

**Comment by marjanasarker** [comment]
Looks amazing, great job on adding comments to every function! My only suggestion as we discussed on our one on one is to add a line asking the user to look at the bottom of the webpage for the game summary

**Review by marjanasarker — APPROVED** [review]
Looks great and great job on getting the ai feature to work seamlessly and adding comments to each function. As I mentioned during our one on one, the only suggestion I have is to add a line directing the user to the bottom of the webpage for the game summary.

**Comment by jsnorek** [comment]
Hi @stmcpeters would you let me know your thoughts on this PR? Thanks!!

**Review by marjanasarker — APPROVED** [review]

**Review by mai-repo — APPROVED** [review]
Looks great!

**Pull request merged**
